# Generated by Django 4.2.3 on 2023-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('experience', models.FloatField()),
                ('salary', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
